### ISSUE TITLE
Error Executing the command lines

### ISSUE THREAD

**Issue by AniLdn** [llSourcell/how_to_convert_text_to_images#2]
Hi,
I have been trying to get this code to run but having the following problems. 

After I download all the required files in a folder called data in the main folder. 

When I run _"python misc/preprocess_birds.py"_  
the error I get ### _bartgs48:how_to_convert_text_to_images research$ python 
                                misc/preprocess_birds.py
                               Traceback (most recent call last):
                               File "misc/preprocess_birds.py", line 10, in <module>
                              from misc.utils import get_image
                             ImportError: No module named misc.utils_

If I try and run the 1st Training command 
                            _"python stageI/run_exp.py --cfg stageI/cfg/birds.yml --gpu 0:_
I get the following error
                          _Traceback (most recent call last):
                            File "stageI/run_exp.py", line 10, in <module>
                           from misc.datasets import TextDataset
                           ImportError: No module named misc.datas_ets

I dont know what am I doing wrong. Please help

**Comment by RJ722** [comment]
You can explicity import it using the command `python -m "misc.utils" misc/preprocess_birds.py` and similarly if any error includes the message: `ImportError: No module named misc.datasets`, you can do `python -m "misc.utils" -m "misc.datasets" whatever-file.py`

**Comment by prankkelkar** [comment]
nothing happens even after running first training example no errors but no output

**Comment by Saahiljeet-Singh** [comment]
It opens up a console of ipdb when I run the train command 
: python run_exp.py --cfg cfg/birds.yml --gpu 0

I get the output as :

Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
--Return--
None

                    stageI/custom_ops.py(136)__call__()
    134                 return input_layer.with_tensor(tf.matmul(input_, matrix) + bias, parameters=self.vars)
    135         except Exception:
    136             import ipdb; ipdb.set_trace()

ipdb> // opens a console here

**Comment by ron-weiner** [comment]
@Saahiljeet-Singh did you solve it?
i'm having the same issue

**Comment by Pettrus** [comment]
You can solve
`ImportError: No module named misc.utils`

using
```
import sys
sys.path.insert(0, 'PATH_TO_YOUR_FOLDER')
```
